name: Hello World # workflow name
on: [push] #events
jobs: # it can contain multiple jobs
  hello: # job name
    runs-on: ubuntu-latest # where to run
    steps:
      - name: Print Hello World
        run: echo "Hello, world!"